"""Event bus — unified publish/subscribe + request/reply for all module coordination."""

from alex.bus.events import (
    Event,
    Command,
    DomainEvent,
    UIEvent,
    UserTurnRequested,
    CronTurnRequested,
    ResumeSessionRequested,
    FeedbackSubmitted,
    ClearSessionRequested,
    TurnStarted,
    SkillMatched,
    ToolExecutionRequested,
    ToolExecutionCompleted,
    TurnCompleted,
    TurnFailed,
    CronScheduled,
    CronTriggered,
    SkillReflected,
    ThinkingUpdated,
    TokenEmitted,
    ToolStarted,
    ToolFinished,
    ToolsProvided,
    ToastRequested,
    SkillLoaded,
    SessionRestored,
    CronBatch,
    CronDone,
    CronError,
    CronJobEvent,
    CronDebugEvent,
    SkillReflectEvent,
    SkillReflectErrorEvent,
    CronRecordPersist,
)
from alex.bus.in_memory import AsyncEventBus

# Re-export kernel bus primitives for convenience
from alex.kernel.bus import (
    Request,
    MessageBus,
    correlation_id,
)
from alex.kernel.errors import (
    CapabilityTimeout,
    CapabilityUnavailable,
    HandlerError,
)

__all__ = [
    # Existing event types
    "Event",
    "Command",
    "DomainEvent",
    "UIEvent",
    "UserTurnRequested",
    "CronTurnRequested",
    "ResumeSessionRequested",
    "FeedbackSubmitted",
    "ClearSessionRequested",
    "TurnStarted",
    "SkillMatched",
    "ToolExecutionRequested",
    "ToolExecutionCompleted",
    "TurnCompleted",
    "TurnFailed",
    "CronScheduled",
    "CronTriggered",
    "SkillReflected",
    "ThinkingUpdated",
    "TokenEmitted",
    "ToolStarted",
    "ToolFinished",
    "ToolsProvided",
    "ToastRequested",
    "SkillLoaded",
    "SessionRestored",
    "CronBatch",
    "CronDone",
    "CronError",
    "CronJobEvent",
    "CronDebugEvent",
    "SkillReflectEvent",
    "SkillReflectErrorEvent",
    "CronRecordPersist",
    # Bus implementation
    "AsyncEventBus",
    # Kernel bus primitives (request/reply)
    "Request",
    "MessageBus",
    "correlation_id",
    # Kernel errors
    "CapabilityTimeout",
    "CapabilityUnavailable",
    "HandlerError",
]
