"""Skill module public interfaces — aligned with real SkillService API."""

from __future__ import annotations

from typing import Any, Protocol


class SkillServicePort(Protocol):
    """Skill lifecycle — matching, loading, reflection, feedback, and CRUD.

    Matches the real SkillService interface.  Agent depends on this
    Protocol, never on SkillRepository or SkillStore internals.
    """

    def retrieve(self, query: str, top_k: int = 3) -> list[Any]: ...

    def inject_skills_prompt(self, query: str) -> str: ...

    def get_skill_by_name(self, name: str) -> Any | None: ...

    async def reflect(self, recent_messages: list, llm: Any, episodes: list[dict] | None = None) -> dict: ...

    def list_all(self) -> list[Any]: ...

    def get_skill(self, skill_id: str) -> Any | None: ...

    def remove_skill(self, skill_id: str) -> None: ...

    def deprecate_skill(self, skill_id: str) -> None: ...

    def record_usage(self, skill_id: str, success: bool) -> None: ...

    async def merge_skills(self, llm: Any) -> dict: ...
